name: DoctorDesk CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: pull DB Image
        run: |
          docker pull victorvcasemiro/doctor-desk-db:doctor-desk-db

      - name: run DB Container
        run: |
          docker run -itd --name doctor-desk-db victorvcasemiro/doctor-desk-db:doctor-desk-db |
          DATASOURCE_IP=`docker container inspect doctor-desk-db --format {{.NetworkSettings.Networks.bridge.IPAddress}}`

      - name: build and running API Container
        run: |
          docker build -t doctor-desk-api --build-arg DATASOURCE_IP=$DATASOURCE_IP . |
          docker run -itd --name doctor-desk-api -e DATASOURCE_IP=$DATASOURCE_IP victorvcasemiro/doctor-desk-api

      - name: Installing K6
        run: sudo gpg -k |
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69 --allow-unauthenticated |
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list |
          sudo apt-get update |
          sudo apt-get install k6

      - name: Running K6
        run: k6 run K6/Get-Pacientes.js