name: DoctorDesk CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  run-project:
    runs-on: ubuntu-latest

    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Running the project
        run: mvn spring-boot:run

      - name: Installing K6
        run: sudo apt-get update |
          sudo apt-get install k6

      - name: Running K6
        run: k6 run K6/Get-Pacientes.js